<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\OpsFlow.Application\OpsFlow.Application.csproj" />
    <ProjectReference Include="..\OpsFlow.Contracts\OpsFlow.Contracts.csproj" />
    <ProjectReference Include="..\OpsFlow.Infrastructure\OpsFlow.Infrastructure.csproj" />
  </ItemGroup>
</Project>
